# Sample config for separated static/dynamic files joined by Name.
input_static: "app/data/wells_static.csv"       # columns: Name, Coord_X, Coord_Y, Bt_Coord_X, Bt_Coord_Y, MD, TVD Pbp
input_dynamic: "app/data/pressures_dynamic.csv" # columns: Name, Pres, BHP

output_dir: "app/out"
csv_sep: ";"

# Map your actual column headers (case-insensitive) to semantic fields
static_columns:
  name: "Name"
  x: "Coord_X"
  y: "Coord_Y"
  bt_x: "Bt_Coord_X"    # Bottom-hole X coordinate
  bt_y: "Bt_Coord_Y"    # Bottom-hole Y coordinate
  md: "MD"              
  tvd: "TVD"
  pbp: "Pbp"    

dynamic_columns:
  name: "Name"
  pres: "Pres"          # optional but at least one of pres/bhp must exist
  bhp: "BHP"            

# Which Z to use if both are present
z_preference: ["bhp","pres"]

# Interpolation settings
interpolation:
  method: "kriging"     # "kriging" | "linear" | "nearest" | "cubic"
  griddata_fallback: "linear"
  kriging:
    variogram_model: "spherical"
    nlags: 6
    enable_plotting: false

grid:
  nx: 600
  ny: 600

bounds_margin_units: 100.0
crs_epsg: 32638

export:
  png: true
  geotiff: true
  geotiff_nodata: -9999

plot:
  figsize: [7, 9]
  cmap: "geology"   # Will use geology.clr if available, fallback to "gist_earth_r"
  draw_contour_labels: true
  show_labels: true
  label_dx: 3
  label_dy: 3
  label_fontsize: 5
  dpi: 600

# Optional label for colorbar
z_label: "Pressure"
